name: cag_mn5
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - absl-py=2.3.1
  - anndata=0.11.4
  - array-api-compat=1.12.0
  - asttokens=3.0.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - comm=0.2.2
  - contourpy=1.3.1
  - cuda-cccl_linux-64=12.4.127
  - cuda-crt-dev_linux-64=12.4.131
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-dev_linux-64=12.4.127
  - cuda-cudart-static=12.4.127
  - cuda-cudart-static_linux-64=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cuobjdump=12.4.127
  - cuda-cupti=12.4.127
  - cuda-driver-dev_linux-64=12.4.127
  - cuda-nvcc=12.4.131
  - cuda-nvcc-dev_linux-64=12.4.131
  - cuda-nvcc-impl=12.4.131
  - cuda-nvcc-tools=12.4.131
  - cuda-nvcc_linux-64=12.4.131
  - cuda-nvdisasm=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-dev_linux-64=12.4.131
  - cuda-nvvm-impl=12.4.131
  - cuda-nvvm-tools=12.4.131
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - cycler=0.11.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - deprecated=1.2.13
  - dm-tree=0.1.9
  - docrep=0.3.2
  - et_xmlfile=2.0.0
  - exceptiongroup=1.2.0
  - executing=2.2.0
  - expat=2.7.1
  - filelock=3.17.0
  - flax=0.6.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fsspec=2025.3.2
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - h5py=3.12.1
  - hdf5=1.14.5
  - icu=73.1
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - legacy-api-wrap=1.4.1
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - libmlir19=19.1.7
  - libnghttp2=1.57.0
  - libnvjitlink=12.4.127
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lightning-utilities=0.15.2
  - lit=19.1.7
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - magma=2.7.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2023.1.0
  - ml-collections=1.0.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - mudata=0.3.2
  - multipledispatch=0.6.0
  - natsort=7.1.1
  - nccl=2.21.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - numba=0.61.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpyro=0.13.2
  - openblas=0.3.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.6.0
  - opentelemetry-api=1.30.0
  - opt_einsum=3.3.0
  - packaging=24.2
  - pandas=2.3.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyopengl=3.1.9
  - pyparsing=3.2.0
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-lightning=1.9.4
  - pytz=2024.1
  - pyzmq=26.2.0
  - readline=8.2
  - rich=14.2.0
  - scanpy=1.11.4
  - scikit-learn=1.6.1
  - scikit-misc=0.5.1
  - scipy=1.15.3
  - seaborn=0.13.2
  - session-info2=0.1.2
  - setuptools=78.1.1
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchmetrics=1.8.2
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - triton=3.1.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - umap-learn=0.5.7
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - benchmark-mi==0.1.3
      - bleach==6.2.0
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - chex==0.1.90
      - cloudpickle==3.1.1
      - defusedxml==0.7.1
      - equinox==0.10.11
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - gast==0.6.0
      - graphviz==0.21
      - grpcio==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hydra-core==1.3.2
      - idna==3.10
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jaxtyping==0.3.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - lark==1.2.2
      - lightning==2.6.0
      - markdown==3.10
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - mpld3==0.5.11
      - multidict==6.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - omegaconf==2.3.0
      - optax==0.1.9
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - prometheus-client==0.22.1
      - propcache==0.4.1
      - protobuf==6.33.4
      - pycparser==2.22
      - pydantic==1.10.24
      - python-json-logger==3.3.0
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - scvi-tools==1.3.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - sparse==0.17.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow-probability==0.20.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.2.1
      - toolz==1.0.0
      - torch-mist==0.2.17
      - types-python-dateutil==2.9.0.20250822
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wadler-lindig==0.1.7
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.14
      - xarray==2025.6.1
      - yarl==1.22.0
prefix: /pool01/conda/envs/cag_mn5
